CREATE TABLE "products" (
	"id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
	"title" TEXT NOT NULL,
	"description" TEXT,
	"author" TEXT NOT NULL,
	"discount" integer NOT NULL,
	"price" integer NOT NULL
);

INSERT INTO public.products (title,description,author,discount,price) VALUES
 ('Ezreho','Zarcu bil dej to le gazmemje veme ibsomi jogal zokup loffif pohfafre vu jugoc. Upsat wohero fabi gizofiuku rudla joej isakuezu buredo zu inavbok birebkif zehjat gi rocafke mol cemum tivmeg. Co zofav zip gec liczac asuru kezu sa uhasu epoaja rizaaz lic iz fapifuda upe. Tefwitmag us holsu moevzi ponu lofibo utoeclol cirtej resigneh raubcu wosrono logen jufughu.','James Brock',0,11),
 ('Motoceluc','Wo fo elu givkukmin felsitve mir pi ad apru av bafus it owe nocbef eve fi zuluk mu. Hig ko nef egati nisapaomi lafaw gikif va gubotpo puilu envom hitnicoh kikewaco itucag pepe. Rolbe cic araf zal felce catne vu ake tudon tu kusedoet al. Pedgiha do dopoweoc ajo zati su era uhwumul ukufuvlem ma kuj huis sehne befvusa besaojo jul.','Clayton Hudson',10,6),
 ('Docemwi','Mulamki uso soupuhov utibon malimijo tuore tomiwiw pe toowahi wuvro owca ze. Uvij peckowal ewbes sior je veso gebreso telope jojij macod dobuffeb fenpel kape ehpe itwot. Muho pup heppi zepu edohosobi awikek anebag ogoronva ufpom mebad mowbuv rohu lico. Ibemuknog juz sitvecak wewjemluj necevib jacisarek jiopidov fo venik rusekukib coeg kemoure.','Owen Bennett',0,13),
 ('Nanubvon','Agusu ezwuwi hunne bocka wobho me li jarotof enafobras hezvigaj humu ano amuade. Fekiru busrizuj be benod ugkahrod lilcisuz uluke wighiun ofecu hebgi ha urcav alnencah pozu fuki fiv deemih cumdaj. Tiso vafbuk jo ejnulut ve bofalo faltedfij ajtiza pas rekav zogihwo rewavuwok uhuvutbuv me. Je bakel zinowoba get pizvoc mucoofa caaforap faka hassodkel kazdaiwo fajig vitos efepihgop.','Kenneth Thornton',40,12),
 ('Ikaefeniw','Kuwjariwo odocuz su jicfasic no utbu umefopfov ajbewew apemi puitig wa um. Okbukej cil huniwisoj pizazur ricoheob sep bahgeb ce mav nu kol ki zerur pud wuubboc faotwaj. Wejiib lohkafwiv raz hesiw tiddenmes oruam ko gahdan pi zukfauj hilzo tu ga utuvaoz espip enlon pepmornir. Gipej jubkule ti tuv rubumubi remlu mepvo nub wesu sigo sij koihwi kidroudo.','Lee Bates',50,12),
 ('Nizodci','Kiw wodurusoh sap dachi muzijej fapebvub ignuik mi wefihfa jen cudas foh luwuipe tolkudged budduj uwenema hamzid hi. Hirvu bipag titer bah uj lan dorej icecusate mincila so tivgafvi hamdoce emlet selfo fepuvo fe suwuca. Ve ed jig rasam la kusaz mahzufi somkodeh dipibaci ema nu aceciani fetsepeg refuw gun zaguzoha palow. Ahoci rijalwuh ojwuto du paw giuh buw kimbogar gu gougje eszoj miazwuw keh azudse.','Calvin Wise',60,15),
 ('Ufkewla','Cum wezaw jij ikiwigef lihubdi fidvigmi ize okbeecu val wenedrap vemim sebudte cupnu acazegal reisga buk ah. Tiwwawe kipnijze tugfen zuicuwo pakhirci roho vik kuru odwanbi ah gituw dewugufu getiknec ob sinwespa jino. Dapjig liimsoh gomluoh zousevez zereuci dosji mibi ve ehpegug lus tihji ro buthifod. Wecu mih raf lezzez isi cisnazbor sot fu mi pede irocumot akuwucum elopu sokim laok jav becihe gi.','Victor Richards',40,17),
 ('Sewewcug','Sijorerum adsamuj vagcirek piftogo jic sizdog raowowi soz atohezvi rasal bi pugaad. Cuaw mofogo obeki nogidiv nur paeme gi sef tuinaku ganhodkoc juv bik huta juge olhu. Jo kemkogun guj sih jig megsaju wanah lujerad pocaf jobe kebiwup lawhih pacogad zurzuot igkimdan keobaped ih pod. Ipudeari kidwecli civ hivi bu terim afnuc uvnib nizolpo hac now bo usi rubo pebo.','Isaiah Grant',30,19),
 ('Ewhema','Inalude cicu wakpuzeb puzjusoj kekmo coszacweb ta ik zugubaha gin gebniko ivumiziju rinufa pab zachol tanaga div kipwevet. Cogovda adhowew puv ejtac haaleje ga ho curmimso ic puztela lahjobni ibioho cot fupanlil ole giwhohoc ihben. Al mohpo hucbuw zubwujwek du berzunuri kur ce pub cawhit ikjoc tozoh. Dilsu vug owbu felcov wevgasgu ha dumwa dizpet vokrov awezajze jito eguhuhih ulju.','Mitchell Paul',20,7),
 ('Ufabikton','Rejulgok nej git pof tu duomuiz encut rewi tikzu nuljocab carpi hozij we. Ocvubde po omijuv madcab ehouv ofbi viv ejzeuze ginezac giwhekih hotdoaka cofedmef vig odewopwub. Zutcilcu bem zoh jel redhovmi are se dile hed duj gu nocuta vu tat ihejezib itwa aji fuuz. Bofdeepi hiwof du zedluza osiwifne lowgo jobworoja cili lim da bibo arga tuzfaz lieki mudi bac pug.','Ian Carlson',30,13);
INSERT INTO public.products (title,description,author,discount,price) VALUES
 ('Fizjoghob','Fuvwaj vovaz lucukkih wudso mu mifvos ja isuode hi linli fej depofaag se siger donac lopapca. Dumimabi cam keb soz negaz foppefoc geha avuusiri lowo avaton luh powoto. Gavtip juf haumedo he kufoso pasnu umudanicu dujod kici tubnu tecadip put. Cacola lednazer zo em raibu so huldevfaf tunanodu puobe levura owe gep uriuz azgudel.','Carl Conner',30,20),
 ('Tivabjog','Ih lini ru ulfawuj durtov wovheta el zoj zoipozu imvov izjugi cobru kas gemomuw gojwufa wo. Kabisuw nugfebiti nisugzi jeoto fug tamanjij zutewo evu vepoveb jarti nareze ki wehihu cuberhij utfajuh giwoeke hibdoris. Zitesjip urapad tidven ekdacis wiwo sumwioga ake efwu ba tu ensucceb bozmalil tuk genudeji mo ejaej. Sov jol pikoguja cudel mew zetzuzon zus likhoilo gom wogvubor lohdu sauko.','Jimmy Quinn',30,5),
 ('Ragpacko','Ahekos sulej guzme sag hiddoroc zaslub odhepzu vud ugo su janapsob rus akni muodoboc fum getajga. Onpuzic gicuko hico saw waetedup be cowup wiefac son pegpim amzuvoza ij cesik ote isuled moku. Haheg vi salijuc wa hih fo kic jicbonled vik luto pafa jeramve. Kopub lawdor niw fof te ro vefip dude ho lucuzo osrosaw lorhir sov.','Jorge Park',10,11),
 ('Ippeaje','Galzezoc izwibpu jumhobac veksaznug han osmad mozzos ik cinfej doisu oz co cagbega zivdioga. Gefabe fovomagu hi hu iv magederi okaja oshosnic lap tup ehok uki godlew masmaki mu obega. Loctaluh ejoawsi pihturoc miknial hiv popgap ocifu urmobo rihbuzzir etuipe hotuh rukrokak likran zule hil sino bewhifle buoho. Rove kub mehevle zefe hulpej wamnil fun idraek wejan zagzaumi alca manakis ro hoppu pol go vogurih.','Erik Smith',60,8),
 ('Vodmurur','Co unemoj unedafum ervocdod fiwacdok benajaw jotkeit zoz waluwaho noamlip baize mum liduja koj su konved ero. Biwvaj obafafmot dolhisul puc ci rubotu seflamfot idhofow lopajza coajabo zunjes putokeve. Cavtazib cef izjidi mot legig fojiwa jeh koko lozbim loiv fubvit mopaghub udi et diwzap fesku guwuz rosraptu. Ad nair vegof zoup zi rofev zeblial ejewut gaig sib hijaki vepowisa ril gupwidwop apeoca ujotazu.','Daniel Terry',10,4),
 ('Foesoto','Ofawovwok ribsipo zu ceazuafu ti gav sapoputi ku ra sumlehzu ki ruakeno isforfi. Jodtuduc bodgel du aruhof zo dunsu muztucuze holsug ji irukifu habwi woovova. Ukhuwu wohpo ewof mishad boho gi tu badvaon low elig gij ba gilgif fipeot joz juhajizi sestij. Utiiz pes cozuha hukozu forjom ewmema pimo er cuc vov ovazihde lal zikahho ronfo vo.','Samuel Miles',0,12),
 ('Powimlar','Upota azcecze fan sojub ilpaw so ca isidifzo hukuni boocujip bat pupbebjoh owoik hudwuw. Ezuwobah ciptiro de mewgagha maaku rijulaed po ave fuihisa oluleaja sacug mewudizif cewsiz beficja. Eca god fivuj si dihel zutcubaw tiz ji nula usitolhe hiwarke nepuf. Elirom juki iv seej pujri oroul ubneodu kab be jigsofa cagdo lugelaz suwi.','Jeremy Obrien',20,18),
 ('Hevjihi','Etkiok vizavsad woh vo pajope nuh kotjam vapwuhko isji semohe hufdegi mo cibojte zahfo vahijpa siaz tugvaib uhiida. Ahejen ese ecufi nuonoar nojefwid hajnu lun eg jisap pupepe janrilvi agi omos atpo bupbu di defiw cavvi. Ce fadsew vugiza tuugsi molne kilawwej aliamok pap monlufsid fi mezbenkus owtim nofuz roz laviw jucibak. Tofsuvco ohhih tole tak az wuuvuju umobaweh kuzihren fueki ra esaca ohwuko.','Austin Parks',40,11),
 ('Tijumous','Ci lobilluf vezurmez ma wiferrud apilo tuigfif ulakugfa ro cal sampieg saupozi hogsa tibkauri rolavole piciwfon. Mipso edako tol lu zow ame bewoje couzaan femgeru otu gad malse zumfeci dufta mijus urtijsul mo. Tefsuplu tib guzomca osowenlok vazwe azonu duavtap gomuf awoawo zo corrin aceke ozpip kabhuha we ugocipha. Dunco hinizac cub fi tico uci iz igu pena gukhev mompesa gacimut apod.','Wesley Baldwin',30,10),
 ('Ipiozfo','Pokci enabofub som kotci uhalu nedinco zuvmijuf ice wi fokpo sar wefavejo uflidig bap fi dewubon. Bur piahvu gamigo me jubudu hipu ercov tuw tu zotaj juporzis je hunup. Neha ule ukuza wi fomhiwi hubu cagufolag fupu kewara tutive nokkijjeg top. Notaju rejevo roze pesde da uru dag ritsiv cadekfa gaveki ojatalor wegvo tejwus mica tohtetli ujtut zoshisrot.','Troy Strickland',50,5);

DROP TABLE "products";